#!/bin/bash

echo "Configure Storm UI..."

if [ -z $ZK_NM ]
  then
    ZK_NM=3
fi

echo "storm.zookeeper.servers:" >> /storm/conf/storm.yaml

until [ $ZK_NM -lt 1 ]; do
  echo "    - \"zookeeper-$ZK_NM\"" >> /storm/conf/storm.yaml
  let ZK_NM-=1
done

echo "nimbus.host: \"nimbus-$NBID\"" >> /storm/conf/storm.yaml

echo "storm.zookeeper.root: \"/storm/$NBID\"" >> /storm/conf/storm.yaml

echo "Finish storm configuration."
echo "[Config] The UI configuration yaml content:-------------------"
cat /storm/conf/storm.yaml
echo "[Config] -------------------------------------------------------------"

./bin/storm ui
